version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${POSTGRES_EXT_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: